# .NET Tool
# Build, run tests for .NET Command Line Tool, pack into a nuget package and publish to internal azure artifacts feed.

trigger:
- {{ branch }}

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
      - job: build_tool
        steps:
        - task: UseDotNet@2
        displayName: 'Install Dot Net'
        inputs:
            version: '5.0.x'

        - task: DotNetCoreCLI@2
        displayName: 'Build Project'
        inputs:
            command: build
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'

        # Run the unit tests and publish the code coverage report
        - task: DotNetCoreCLI@2
        displayName: 'Run Unit Tests'
        inputs:
            command: 'test'
            arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
            publishTestResults: true
            projects: '**/*.Tests'

        - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage report'
        inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

        # Pack the project into a NuGet package 
        - task: DotNetCoreCLI@2
        inputs: 
            command: 'pack'
            packagesToPack: '**/*.csproj'
            outputDir: '$(Build.ArtifactStagingDirectory)'
            versioningScheme: byBuildNumber
        displayName: 'Pack the project'

        # Push package to internal organization Feed with the format (Project Name/Name of Feed) in the feedPublish input.
        - task: DotNetCoreCLI@2
        inputs:
            command: 'push'
            searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.Tests.nupkg'
            feedPublish: 'testProject/testFeed'
        displayName: 'Publish nuget package to feed'
